//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Sos.Negocio.Entidades", "FK_UsuarioEnderecos", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sos.Negocio.Entidades.Usuario), "Endereco", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sos.Negocio.Entidades.Endereco), true)]
[assembly: EdmRelationshipAttribute("Sos.Negocio.Entidades", "FK_CategoriaProdutoProduto", "CategoriaProduto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sos.Negocio.Entidades.CategoriaProduto), "Produto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sos.Negocio.Entidades.Produto), true)]
[assembly: EdmRelationshipAttribute("Sos.Negocio.Entidades", "FK_UsuarioTelefone", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sos.Negocio.Entidades.Usuario), "Telefone", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sos.Negocio.Entidades.Telefone), true)]
[assembly: EdmRelationshipAttribute("Sos.Negocio.Entidades", "FK_Produto_Casco", "Casco", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Sos.Negocio.Entidades.Casco), "Produto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sos.Negocio.Entidades.Produto), true)]

#endregion

namespace Sos.Negocio.Entidades
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ModelSosContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ModelSosContainer object using the connection string found in the 'ModelSosContainer' section of the application configuration file.
        /// </summary>
        public ModelSosContainer() : base("name=ModelSosContainer", "ModelSosContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModelSosContainer object.
        /// </summary>
        public ModelSosContainer(string connectionString) : base(connectionString, "ModelSosContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModelSosContainer object.
        /// </summary>
        public ModelSosContainer(EntityConnection connection) : base(connection, "ModelSosContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Endereco> Endereco
        {
            get
            {
                if ((_Endereco == null))
                {
                    _Endereco = base.CreateObjectSet<Endereco>("Endereco");
                }
                return _Endereco;
            }
        }
        private ObjectSet<Endereco> _Endereco;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CategoriaProduto> CategoriaProduto
        {
            get
            {
                if ((_CategoriaProduto == null))
                {
                    _CategoriaProduto = base.CreateObjectSet<CategoriaProduto>("CategoriaProduto");
                }
                return _CategoriaProduto;
            }
        }
        private ObjectSet<CategoriaProduto> _CategoriaProduto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Produto> Produto
        {
            get
            {
                if ((_Produto == null))
                {
                    _Produto = base.CreateObjectSet<Produto>("Produto");
                }
                return _Produto;
            }
        }
        private ObjectSet<Produto> _Produto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Telefone> Telefone
        {
            get
            {
                if ((_Telefone == null))
                {
                    _Telefone = base.CreateObjectSet<Telefone>("Telefone");
                }
                return _Telefone;
            }
        }
        private ObjectSet<Telefone> _Telefone;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Casco> Casco
        {
            get
            {
                if ((_Casco == null))
                {
                    _Casco = base.CreateObjectSet<Casco>("Casco");
                }
                return _Casco;
            }
        }
        private ObjectSet<Casco> _Casco;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Endereco EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEndereco(Endereco endereco)
        {
            base.AddObject("Endereco", endereco);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CategoriaProduto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategoriaProduto(CategoriaProduto categoriaProduto)
        {
            base.AddObject("CategoriaProduto", categoriaProduto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Produto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProduto(Produto produto)
        {
            base.AddObject("Produto", produto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Telefone EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTelefone(Telefone telefone)
        {
            base.AddObject("Telefone", telefone);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Casco EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCasco(Casco casco)
        {
            base.AddObject("Casco", casco);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sos.Negocio.Entidades", Name="Casco")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Casco : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Casco object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="preco">Initial value of the Preco property.</param>
        public static Casco CreateCasco(global::System.Int32 id, global::System.Decimal preco)
        {
            Casco casco = new Casco();
            casco.Id = id;
            casco.Preco = preco;
            return casco;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Preco
        {
            get
            {
                return _Preco;
            }
            set
            {
                OnPrecoChanging(value);
                ReportPropertyChanging("Preco");
                _Preco = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Preco");
                OnPrecoChanged();
            }
        }
        private global::System.Decimal _Preco;
        partial void OnPrecoChanging(global::System.Decimal value);
        partial void OnPrecoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sos.Negocio.Entidades", Name="CategoriaProduto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CategoriaProduto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CategoriaProduto object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static CategoriaProduto CreateCategoriaProduto(global::System.Int32 id, global::System.String nome)
        {
            CategoriaProduto categoriaProduto = new CategoriaProduto();
            categoriaProduto.Id = id;
            categoriaProduto.Nome = nome;
            return categoriaProduto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sos.Negocio.Entidades", "FK_CategoriaProdutoProduto", "Produto")]
        public EntityCollection<Produto> Produtos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Produto>("Sos.Negocio.Entidades.FK_CategoriaProdutoProduto", "Produto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Produto>("Sos.Negocio.Entidades.FK_CategoriaProdutoProduto", "Produto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sos.Negocio.Entidades", Name="Endereco")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Endereco : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Endereco object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="rua">Initial value of the Rua property.</param>
        /// <param name="numero">Initial value of the Numero property.</param>
        /// <param name="bairro">Initial value of the Bairro property.</param>
        /// <param name="cidade">Initial value of the Cidade property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        /// <param name="usuarioEnderecos_Endereco_Id">Initial value of the UsuarioEnderecos_Endereco_Id property.</param>
        public static Endereco CreateEndereco(global::System.Int32 id, global::System.String rua, global::System.Int32 numero, global::System.String bairro, global::System.String cidade, global::System.String estado, global::System.Int32 usuarioEnderecos_Endereco_Id)
        {
            Endereco endereco = new Endereco();
            endereco.Id = id;
            endereco.Rua = rua;
            endereco.Numero = numero;
            endereco.Bairro = bairro;
            endereco.Cidade = cidade;
            endereco.Estado = estado;
            endereco.UsuarioEnderecos_Endereco_Id = usuarioEnderecos_Endereco_Id;
            return endereco;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Rua
        {
            get
            {
                return _Rua;
            }
            set
            {
                OnRuaChanging(value);
                ReportPropertyChanging("Rua");
                _Rua = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Rua");
                OnRuaChanged();
            }
        }
        private global::System.String _Rua;
        partial void OnRuaChanging(global::System.String value);
        partial void OnRuaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.Int32 _Numero;
        partial void OnNumeroChanging(global::System.Int32 value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Complemento
        {
            get
            {
                return _Complemento;
            }
            set
            {
                OnComplementoChanging(value);
                ReportPropertyChanging("Complemento");
                _Complemento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Complemento");
                OnComplementoChanged();
            }
        }
        private global::System.String _Complemento;
        partial void OnComplementoChanging(global::System.String value);
        partial void OnComplementoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Bairro
        {
            get
            {
                return _Bairro;
            }
            set
            {
                OnBairroChanging(value);
                ReportPropertyChanging("Bairro");
                _Bairro = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Bairro");
                OnBairroChanged();
            }
        }
        private global::System.String _Bairro;
        partial void OnBairroChanging(global::System.String value);
        partial void OnBairroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cidade
        {
            get
            {
                return _Cidade;
            }
            set
            {
                OnCidadeChanging(value);
                ReportPropertyChanging("Cidade");
                _Cidade = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Cidade");
                OnCidadeChanged();
            }
        }
        private global::System.String _Cidade;
        partial void OnCidadeChanging(global::System.String value);
        partial void OnCidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UsuarioEnderecos_Endereco_Id
        {
            get
            {
                return _UsuarioEnderecos_Endereco_Id;
            }
            set
            {
                OnUsuarioEnderecos_Endereco_IdChanging(value);
                ReportPropertyChanging("UsuarioEnderecos_Endereco_Id");
                _UsuarioEnderecos_Endereco_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UsuarioEnderecos_Endereco_Id");
                OnUsuarioEnderecos_Endereco_IdChanged();
            }
        }
        private global::System.Int32 _UsuarioEnderecos_Endereco_Id;
        partial void OnUsuarioEnderecos_Endereco_IdChanging(global::System.Int32 value);
        partial void OnUsuarioEnderecos_Endereco_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sos.Negocio.Entidades", "FK_UsuarioEnderecos", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("Sos.Negocio.Entidades.FK_UsuarioEnderecos", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("Sos.Negocio.Entidades.FK_UsuarioEnderecos", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("Sos.Negocio.Entidades.FK_UsuarioEnderecos", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("Sos.Negocio.Entidades.FK_UsuarioEnderecos", "Usuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sos.Negocio.Entidades", Name="Produto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Produto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Produto object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="precoAntigo">Initial value of the PrecoAntigo property.</param>
        /// <param name="disponivel">Initial value of the Disponivel property.</param>
        /// <param name="imagem">Initial value of the Imagem property.</param>
        /// <param name="categoria_Id">Initial value of the Categoria_Id property.</param>
        public static Produto CreateProduto(global::System.Int32 id, global::System.String nome, global::System.Decimal precoAntigo, global::System.Boolean disponivel, global::System.String imagem, global::System.Int32 categoria_Id)
        {
            Produto produto = new Produto();
            produto.Id = id;
            produto.Nome = nome;
            produto.PrecoAntigo = precoAntigo;
            produto.Disponivel = disponivel;
            produto.Imagem = imagem;
            produto.Categoria_Id = categoria_Id;
            return produto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Preco
        {
            get
            {
                return _Preco;
            }
            set
            {
                OnPrecoChanging(value);
                ReportPropertyChanging("Preco");
                _Preco = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Preco");
                OnPrecoChanged();
            }
        }
        private Nullable<global::System.Decimal> _Preco;
        partial void OnPrecoChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PrecoAntigo
        {
            get
            {
                return _PrecoAntigo;
            }
            set
            {
                OnPrecoAntigoChanging(value);
                ReportPropertyChanging("PrecoAntigo");
                _PrecoAntigo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecoAntigo");
                OnPrecoAntigoChanged();
            }
        }
        private global::System.Decimal _PrecoAntigo;
        partial void OnPrecoAntigoChanging(global::System.Decimal value);
        partial void OnPrecoAntigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Disponivel
        {
            get
            {
                return _Disponivel;
            }
            set
            {
                OnDisponivelChanging(value);
                ReportPropertyChanging("Disponivel");
                _Disponivel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Disponivel");
                OnDisponivelChanged();
            }
        }
        private global::System.Boolean _Disponivel;
        partial void OnDisponivelChanging(global::System.Boolean value);
        partial void OnDisponivelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Imagem
        {
            get
            {
                return _Imagem;
            }
            set
            {
                OnImagemChanging(value);
                ReportPropertyChanging("Imagem");
                _Imagem = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Imagem");
                OnImagemChanged();
            }
        }
        private global::System.String _Imagem;
        partial void OnImagemChanging(global::System.String value);
        partial void OnImagemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Categoria_Id
        {
            get
            {
                return _Categoria_Id;
            }
            set
            {
                OnCategoria_IdChanging(value);
                ReportPropertyChanging("Categoria_Id");
                _Categoria_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Categoria_Id");
                OnCategoria_IdChanged();
            }
        }
        private global::System.Int32 _Categoria_Id;
        partial void OnCategoria_IdChanging(global::System.Int32 value);
        partial void OnCategoria_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Casco_Id
        {
            get
            {
                return _Casco_Id;
            }
            set
            {
                OnCasco_IdChanging(value);
                ReportPropertyChanging("Casco_Id");
                _Casco_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Casco_Id");
                OnCasco_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Casco_Id;
        partial void OnCasco_IdChanging(Nullable<global::System.Int32> value);
        partial void OnCasco_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sos.Negocio.Entidades", "FK_CategoriaProdutoProduto", "CategoriaProduto")]
        public CategoriaProduto Categoria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CategoriaProduto>("Sos.Negocio.Entidades.FK_CategoriaProdutoProduto", "CategoriaProduto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CategoriaProduto>("Sos.Negocio.Entidades.FK_CategoriaProdutoProduto", "CategoriaProduto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CategoriaProduto> CategoriaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CategoriaProduto>("Sos.Negocio.Entidades.FK_CategoriaProdutoProduto", "CategoriaProduto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CategoriaProduto>("Sos.Negocio.Entidades.FK_CategoriaProdutoProduto", "CategoriaProduto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sos.Negocio.Entidades", "FK_Produto_Casco", "Casco")]
        public Casco Casco
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Casco>("Sos.Negocio.Entidades.FK_Produto_Casco", "Casco").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Casco>("Sos.Negocio.Entidades.FK_Produto_Casco", "Casco").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Casco> CascoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Casco>("Sos.Negocio.Entidades.FK_Produto_Casco", "Casco");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Casco>("Sos.Negocio.Entidades.FK_Produto_Casco", "Casco", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sos.Negocio.Entidades", Name="Telefone")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Telefone : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Telefone object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="numero">Initial value of the Numero property.</param>
        /// <param name="tipo">Initial value of the Tipo property.</param>
        /// <param name="usuarioTelefone_Id">Initial value of the UsuarioTelefone_Id property.</param>
        public static Telefone CreateTelefone(global::System.Int32 id, global::System.String numero, global::System.String tipo, global::System.Int32 usuarioTelefone_Id)
        {
            Telefone telefone = new Telefone();
            telefone.Id = id;
            telefone.Numero = numero;
            telefone.Tipo = tipo;
            telefone.UsuarioTelefone_Id = usuarioTelefone_Id;
            return telefone;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.String _Numero;
        partial void OnNumeroChanging(global::System.String value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UsuarioTelefone_Id
        {
            get
            {
                return _UsuarioTelefone_Id;
            }
            set
            {
                OnUsuarioTelefone_IdChanging(value);
                ReportPropertyChanging("UsuarioTelefone_Id");
                _UsuarioTelefone_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UsuarioTelefone_Id");
                OnUsuarioTelefone_IdChanged();
            }
        }
        private global::System.Int32 _UsuarioTelefone_Id;
        partial void OnUsuarioTelefone_IdChanging(global::System.Int32 value);
        partial void OnUsuarioTelefone_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sos.Negocio.Entidades", "FK_UsuarioTelefone", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("Sos.Negocio.Entidades.FK_UsuarioTelefone", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("Sos.Negocio.Entidades.FK_UsuarioTelefone", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("Sos.Negocio.Entidades.FK_UsuarioTelefone", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("Sos.Negocio.Entidades.FK_UsuarioTelefone", "Usuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sos.Negocio.Entidades", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="senha">Initial value of the Senha property.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.String email, global::System.String senha)
        {
            Usuario usuario = new Usuario();
            usuario.Id = id;
            usuario.Email = email;
            usuario.Senha = senha;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sos.Negocio.Entidades", "FK_UsuarioEnderecos", "Endereco")]
        public EntityCollection<Endereco> Enderecos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Endereco>("Sos.Negocio.Entidades.FK_UsuarioEnderecos", "Endereco");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Endereco>("Sos.Negocio.Entidades.FK_UsuarioEnderecos", "Endereco", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sos.Negocio.Entidades", "FK_UsuarioTelefone", "Telefone")]
        public EntityCollection<Telefone> Telefones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Telefone>("Sos.Negocio.Entidades.FK_UsuarioTelefone", "Telefone");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Telefone>("Sos.Negocio.Entidades.FK_UsuarioTelefone", "Telefone", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
